# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3a5bcddeeb0b36d12f2da14852ae1376"
name = "ITestApp"
handle = "itestapp"
application_url = "https://img-theatre-preservation-tender.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "private-dev-ilyosbek.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://img-theatre-preservation-tender.trycloudflare.com/auth/callback",
  "https://img-theatre-preservation-tender.trycloudflare.com/auth/shopify/callback",
  "https://img-theatre-preservation-tender.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
